cz[0] = ["volitelný,jiný možný(ne optiona",
        "klávesy šipek",
        "hvězdička",
        "zálohovat (ne store=uložit)",
        "obrácené lomítko",
        "řádkové menu",
        "blikat",
        "rámeček (ne frame)",
        "přerušit(ne abort,interrupt,sus",
        "vestavět, vestavěný",
        "zrušit,stornovat(ne discard)",
        "velké písmeno(ne uppercase)",
        "deska, karta",
        "kapitola",
        "znak (ne sign)",
        "vymazat(ne delete,clear,remove",
        "zavřít",
        "dvojtečka",
        "sloupec",
        "čárka ve větě",
        "zkrátit,vyjmout,vystřihnout",
        "pomlčka (ne hyphen)",
        "hustota",
        "tečka, bod (ne point)",
        "disková mechanika",
        "kopírování (ne copying)",
        "upravit (text)(ne modify,change",
        "selhat, nepodařit se",
        "vada,chyba(ne failure,error,mis",
        "číslice, diagram, obrázek",
        "najít",
        "všeobecný(ne common,universal)",
        "průvodce (ne wizard)",
        "skrýt,schovat",
        "pomlčka (ne dash)",
        "úvod",
        "neplatný (ne void)",
        "písmeno",
        "řádek (ne row)",
        "odřádkování",
        "zamknout,znepřístupnit",
        "vyhledání (ne search)",
        "hodit se pasovat",
        "matice",
        "příští,další(ne following)",
        "všimnout si",
        "připojený(tiskárna)",
        "přepsat (ne rewrite)",
        "stránka",
        "část (ne portion, section)",
        "sbírat,vybírat(ne select,collec",
        "chránit,bránit",
        "tlačit,stisknout(ne press)",
        "opustit,ukončit (ne cancel,exi",
        "opustit(ne quit,cancel,leave)",
        "připraven",
        "nahradit",
        "znovu začít",
        "zkusit znovu (ne resume)",
        "přepsat (ne ovewrite)",
        "páska (ne tape)",
        "řada, řádek (ne line)",
        "uložit, uschovat (ne store)",
        "hledat(ne search,scan)",
        "procházet,prohledávat(ne seek)",
        "vybrat (ne choose, pick)",
        "středník",
        "věta",
        "nastavit (ne adjust)",
        "posun,přeřaďovač",
        "velikost,rozměr",
        "lomítko",
        "stojící samostatně(ne single)",
        "uložit(data) (ne save),úložiště",
        "zapnout (ne turn on)",
        "teplota",
        "přepínat (ne switch,swap)",
        "téma (ne theme)",
        "celkový(ne overall),celk.součet",
        "stopa, sledovat",
        "neautorizovaný",
        "aktualizovaný(ne refreshed)",
        "pohled, prohlédnout",
        "dvojkový",
        "úroveň (ne grade)",
        "nedostatečný",
        "prázdný (ne blank)",
        "zadat, vložit (ne insert)",
        "datum",
        "jistý (ne certain)",
        "chybět",
        "neúspěch,závada,porucha(ne faul",
        "obnovit(ne restore,update,refre",
        "pokračovat(ne continue,resume)",
        "jiný, další (ne other,next)",
        "skrytý",
        "více",
        "krátký, stručný (ne short)",
        "plný,nezkrácený(např.výpis)",
        "přepínat (ne switch,toggle)",
        "viditelný",
        "rychlý (ne quick)",
        "ani, žádný",
        "dokonce i"];


cz[1] = [ "strom",
        "adresář s podřízenými adr.",
        "komprimovat (ne pack)",
        "stisknout (ne push, hit)",
        "jakýkoliv",
        "příkazy šedě(nepřístupné)",
        "nepřístupný (příkaz)(ne unreach",
        "pasivovat zaškrt.políčko",
        "vybrat zaškrtávací políčko",
        "částečně vybrané zaškrt.pol.",
        "velikost písma",
        "velikost písma v bodech",
        "tučný",
        "kurzíva",
        "podtržený (ne underscored)",
        "podsazení, dolní index",
        "nadsazení, horní index",
        "textový kurzor",
        "kurzor myši",
        "klávesová zkratka,zástupce",
        "táhni a pusť",
        "posuvník(přetáčecí lišta)",
        "požadavek,nároky(ne demand)",
        "ponechat",
        "beze změn(ne without change",
        "původní,počáteční(ne original)",
        "doporučovat",
        "přinejmenším",
        "podle potřeby",
        "používá se",
        "ze seznamu",
        "šetřič obrazovky",
        "velké (písmeno ne capital)",
        "malé (písmeno)",
        "stavový řádek, pruh (ne line)",
        "přílohy",
        "znak konce odstavce",
        "výskyt (ne presence)",
        "kontrola",
        "opravit (ne repair)",
        "nastavit pozici(ne set...)",
        "prázdný řádek (ne empty)",
        "vybraný text (ne selected)",
        "obrysy (ne border: okraj)",
        "přerušit(ne break,abort,suspend",
        "šablona (styl dokumentu)",
        "popisek(např.obrázku,ne descrip",
        "táhnout (ne pull)",
        "změnit velikost",
        "vzhledem k(ne according to)",
        "sbalit (nabídku,ne soubor)",
        "rozbalit (ne explode)",
        "povýšit,zvýšit hierar. úroveň",
        "snížit (hierar. úroveň)",
        "příruční (místní) nabídka",
        "upravit,upravit si(ne modify)",
        "pravopis",
        "korektor překlepů",
        "poznámky (ne notes)",
        "souhrnné informace",
        "ukázka před tiskem",
        "záhlaví,hlavička(ne heading)",
        "pata, patička",
        "velikost papíru",
        "na výšku (orientace",
        "na šířku (orientace)",
        "odstavec",
        "zarovnání (odstavce)",
        "naposledy použité(ne lastly...)",
        "rozlišovat malá a velká",
        "rozlišení velkých písmen(ne mat",
        "nástrojový pruh",
        "dopředu",
        "dozadu",
        "tabulkový procesor",
        "buňka tabulky",
        "zadávat data",
        "desetinná místa",
        "zalamování textu",
        "přetékat (do soused.buněk)",
        "rovnítko",
        "operátor dělení",
        "operátor sčítání",
        "odčítání",
        "větší než",
        "roven",
        "menší než",
        "není roven",
        "odkaz na buňku",
        "koláčový (výsečový) graf",
        "dlaždice",
        "zvětšení(ne zoom,enlargement)",
        "seřadit podle (ne arrange)",
        "vzestupně (seřadit)",
        "sestupně (seřadit)" ];

cz[2] = [ "víko (notebooku)",
        "spánek",
        "známý",
        "omezení(ne constraints,limit)",
        "patřit",
        "jedinečný",
        "přiřazení",
        "vypršet",
        "pasivovat,zneschopnit(ne disabl",
        "práva",
        "zrušit (ne discard,cancel)",
        "všichni (ne all)",
        "skupina, seskupit",
        "řada, fronta",
        "stav",
        "připojit(ne join,connect,link",
        "přihlásit",
        "uvědomit",
        "služba",
        "rovný s rovným",
        "vetřelec",
        "uzamčení",
        "nouze, havárie",
        "malé zdokonalení programu",
        "zůstat (ne stay)",
        "potlačit",
        "popis",
        "odmítnout (refuse)",
        "zadržet (ne retain)",
        "odsunout, pozdržet",
        "pořadí (ne order)",
        "zařadit tisk.úlohu do front",
        "podle",
        "vzor (maska) hledání",
        "pověřenec, důvěrník",
        "zrušit,stornovat(ne cancel)",
        "oddělovač (položek seznamu)",
        "vyhrazený",
        "kopie (ne copy)",
        "včetně",
        "výhoda",
        "bez ohledu na",
        "dříve než",
        "týkající se(ne concerning)",
        "podezřívat",
        "ztráta",
        "čitelný",
        "přibližný",
        "trpět",
        "zlepšit",
        "týkat se (ne regard)",
        "účel",
        "odhadnout",
        "uzel",
        "dotaz (ne request,question)",
        "spolehlivost",
        "vydání (ne issue,release)",
        "za předpokladu",
        "dodávka",
        "moudrý,rozumný(ne reasonable",
        "porušit, přestoupit",
        "smysl",
        "prospěch",
        "vyvolat (ne invoke)",
        "nabídnout",
        "zahrnovat(ne include,contain)",
        "chod, tempo",
        "nezbytný, nutný",
        "žádost,požadavek(ne request",
        "podobný (ne like)",
        "spojit,připojit(ne attach,link",
        "dodavatel, obchodník",
        "způsob (ne way)",
        "důvod",
        "sídlit",
        "sada, komplet (ne set,kit)",
        "sada, komplet (ne set,suite)",
        "úroveň (ne level)",
        "sledovaní událostí",
        "letní čas",
        "předávání",
        "rámec (protokolový)",
        "protokolový soubor",
        "důležitý, základní, hlavní",
        "využívat (ne use, utilize)",
        "využívat(ne use,take advantage)",
        "nezávislý, samostatný",
        "zdali",
        "popisovat",
        "umístit (ne place,deploy)",
        "hlavní(ne fundamental,main)",
        "provádět,zpracovávat(ne execut",
        "nefunkční",
        "přímý, nasměrovat",
        "zkratka (ne shortcut)",
        "rozlišovat",
        "odlišný (ne alternate)",
        "shromáždit (ne collect)",
        "odpovědnost",
        "vrstva",
        "termín",
        "výstraha,pozornost,opatrnost)",
        "po dokončení",
        "široké spektrum",
        "ladit",
        "příkaz (v programu)",
        "příkaz, povel (např. v MSDOS)",
        "náhodný (ve významu nehody)",
        "příležitostný,náhodný(ne random",
        "příležitostný,náhodný (ne occas"];

cz[3] = [ "přístrojová deska auta",
        "přesný (ne precise)",
        "celkový (ne total)",
        "různý(ne different,miscellaneo",
        "předpokládat",
        "poznat",
        "postup,pokrok (ne progress)",
        "proveditelný",
        "umístěný (ne located)",
        "tok (ne stream)",
        "spustit,uvést v chod",
        "zvýraznit (ne mark-označit)",
        "kromě (ne besides)",
        "složený",
        "za, mimo, nad",
        "obejít (ne override)",
        "úsilí,snaha",
        "stálý,trvalý(ne parmanent)",
        "používat,využívat(ne use,utiliz",
        "zastaralý(ne outdated,legacy)",
        "v souladu s",
        "odpovídat čemu, splňovat",
        "hlavní panel",
        "provést(ne perform,execute,acco",
        "získat(ne obtain,gain,acquire)",
        "získat(ne get,gather,acquire)",
        "získat(ne gain,win,get,obtain)",
        "získat(ne acquire,win,obtain,ge",
        "současný",
        "připojení (ne link)",
        "samostatný",
        "drátem připojený",
        "vazba, provázání",
        "pořadí prohledávání",
        "výkon (ne power)",
        "poslat",
        "nepřerušitelný",
        "zdroj napájení",
        "vybitá baterie",
        "místní (ne native)",
        "doba trvání hesla",
        "povolit (ne allow, approve)",
        "rozprostřený",
        "nečinný",
        "poslední známý",
        "cestovat, toulat se",
        "oznamovací tón",
        "vyloučit oblast (ne area)",
        "automatizovat",
        "zavěsit, odpojit linku",
        "vysílat (ne broadcast)",
        "výzva, náročný úkol(ne prompt)",
        "odezva, reakce (ne reaction)",
        "odpovídat na,reagovat",
        "trvání propůjčení",
        "důvěřovat",
        "nejvíce omezující",
        "omezit přístup (ne deny)",
        "bezobslužný,bez přítomnosti",
        "být přítomen",
        "volba (ne selection, choice)",
        "ověření(ne authentication,verif",
        "mn.č. od mouse",
        "průchodnost",
        "závažný (ne serious)",
        "jednoduchý",
        "udržovat, zachovat",
        "údržba",
        "volba (ne option, choice)",
        "navrhovat (ne suggest)",
        "nasadit,zavést do praxe,realizo",
        "poskytovat",
        "zvýšit",
        "prozradit, odkrýt",
        "režie",
        "doručit, dodat",
        "simulovat",
        "poškodit",
        "odstranit,vyloučit(ne exclude)",
        "schopnost (ne ability)",
        "citlivý",
        "výrazný (ne highlighted)",
        "zachovat si,ponechat(ne preserv",
        "zachovat,uchovat(ne retain)",
        "efektivní, výkonný",
        "rozpětí,rozsah(ne scope,range)",
        "pravidelný",
        "potkat (ne meet)",
        "všeobecně použitelný",
        "způsobovat,důvod,příčina",
        "čekající na vyřízení",
        "vyhnout se",
        "obejít (ne bypass)",
        "použitelný (ne usable)",
        "podmnožina",
        "zajistit (ne ensure,assert)",
        "zajistit(ne ensure,guarantee)",
        "zajistit(ne assert,guarantee)",
        "zatížení, důraz",
        "zacházet,manipulovat(ne manipu",
        "měřit",
        "čítač",
        "loudavý",
        "přílišný",
        "uváznutý",
        "volný (ne free)",
        "zničený,porušený(ne damaged)",
        "vyrovnávací paměť",
        "všesměrový paket",
        "vyrovnávání zatížení",
        "řešení jména",
        "dopředné čtení",
        "dědění práv",
        "přípojka (port)",
        "odkládací soubor"];

cz[4] = [ "dosáhnout (ne reach)",
        "výstraha, poplach",
        "pokračovat (ne proceed,resume)",
        "podnikový, firemní",
        "cíl",
        "určit,rozhodnout(ne decide)",
        "vybavený",
        "odchozí",
        "zastaralý,starší verze(ne obsol",
        "stálý,trvalý(ne persistent)",
        "připravovat",
        "dosáhnout (ne achieve)",
        "předložit, podat",
        "dočasný",
        "jednotka",
        "využití (ne usage)",
        "most",
        "knoflík, tlačítko",
        "žádoucí, vhodný",
        "přípona, prodloužení",
        "často (ne often)",
        "vstup (ne entry)",
        "položka",
        "zámek, ochrana",
        "nedávný,minulý(ne last,previou",
        "uskutečnit,vykonat(ne execute)",
        "odpovídající,splňující požad.",
        "soulad s, vyhovění čemu, dodržo",
        "potvrdit (ne acknowledge)",
        "podnik",
        "povinný (ne obligatory)",
        "zakázaný(ne denied,restricted)",
        "oprava (ne correction),opravit",
        "špatný",
        "prohlížet",
        "okolí, prostředí",
        "spustit,vykonat(ne perform,laun",
        "určitý,konkrétní(ne specific)",
        "oblast (ne area, scope)",
        "výsledek",
        "podpis",
        "zdroj (ne supply,resource)",
        "zdroj (ne supply,source)",
        "zdroj (ne resource,source)",
        "pruh",
        "trasa, následovat,kopírovat",
        "platný",
        "hodnota",
        "pozadí",
        "jistý (ne sure)",
        "výjimka",
        "neúspěšný (ne unsuccessful)",
        "pokrok (ne advance)",
        "za předpokladu, že",
        "příbuzný",
        "uvolnit(např.tlačítko myši)",
        "řešit",
        "přes",
        "uvnitř, v mezích",
        "schopnost (ne capability)",
        "slučitelnost",
        "denně",
        "položka, vstup (ne input)",
        "příklad",
        "rychle (ne fast)",
        "přijmout (ne receive)",
        "příchozí",
        "vsunout, vložit",
        "původní (ne initial)",
        "část (ne part)",
        "oddělený",
        "chytrý (ne wise, clever)",
        "ověření(ne authentication,valid",
        "objevit se (ne occur)",
        "objevit se,nastat(ne appear,hap",
        "případ (ne event)",
        "pověření (jméno a konto)",
        "zakázat(ne prohibit,restrict)",
        "režim spánku",
        "spoj, spojit (ne join)",
        "prostředek",
        "bod (ne dot)",
        "společný fond",
        "obrazovka",
        "nástroj",
        "odlišný,alternativní(ne differe",
        "odhalení,detekce",
        "odpojit (ne detach)",
        "správný (ne correct)",
        "hledat(ne seek,scan,lookup)",
        "odstraňovat chyby (ne debug)",
        "množství",
        "kazeta",
        "připojitelnost,kvalita přip.",
        "zkoumat (ne explore)",
        "hostitel, hostit",
        "vícenásobný, mnohý",
        "násobit",
        "poznámka",
        "vlastnictví",
        "znovu nastavit",
        "řešení problémů",
        "obsah",
        "umístit,nasadit(ne locate,place",
        "podobně(ne similarly)",
        "vyjmenovaný,zapsaný v sezn",
        "výzva (v přík.řádku),podnět",
        "bezpečný (ne secure)",
        "dodatečný, další",
        "pruh (ne stripe)",
        "založený na",
        "šifrovat",
        "rozbočovač",
        "vydání(needition,release),vydat",
        "jazyk",
        "zhustit,stlačit(ne compress)",
        "oddíl",
        "technik",
        "rys, vlastnost(ne property)",
        "zavést do paměti (ne boot)",
        "umístění",
        "předchozí",
        "žádat,žádost(ne require,demand)",
        "řešení, překlad, rozlišení",
        "kdykoliv",
        "zaměstnanec",
        "zahrnout (ne comprise)" ];

cz[5] = [ "přesunout (ne shift)",
        "balíček",
        "osobní",
        "bez znaménka",
        "vývoj",
        "člen",
        "cesta (k souboru)",
        "sezení",
        "aktuální (ne up to date)",
        "zvyk",
        "událost (ne case)",
        "obraz",
        "několik (ne some)",
        "zastaralý,starší verze(ne obso",
        "tudíž,tedy (ne so, therefore)",
        "příslušný,odpovídající(ne corre",
        "přiřadit",
        "koláček",
        "kořen",
        "bezdrátový",
        "řadič",
        "ustavit, založit, zřídit",
        "uvést, prohlásit",
        "neschopen",
        "objevit,najít,zjistit(ne find)",
        "ještě, nadto, kromě toho",
        "soukromý",
        "cestovní (ne travel)",
        "úložné místo, paměť",
        "přepínač, volba",
        "čaroděj, přeneseně:průvodce",
        "ovlivnit",
        "vymazat(ne erase,clear,remo",
        "přírůstkový",
        "umístěný(ne placed,deployed)",
        "běžící",
        "řešení",
        "důvěryhodný",
        "ověření při přihlašování",
        "klávesa",
        "výzkum",
        "vytočit",
        "vyřešit, přeložit",
        "skrz",
        "zavést op.systém do paměti",
        "vymazat(ne delete,erase,remo",
        "úkol, úloha (ne job)",
        "úspěšně",
        "obnovit,aktualizovat(ne restore",
        "pokus, pokusit se (ne try)",
        "vybrat (ne select, pick)",
        "vyžadovat(ne request,demand",
        "sestávat se z, skládat se z",
        "pružný",
        "velké zdokonal. programu",
        "správce",
        "pokročilý",
        "změnit",
        "spravovat,řídit(ne control)",
        "zpráva, hlásit",
        "mezera,prostor",
        "záložka (listu v Excelu)",
        "použít, aplikovat (ne use)",
        "ovladač",
        "dělit se o, sdílet",
        "provést (ne commit,execute)",
        "směrovač",
        "rozhraní",
        "zabránit čemu",
        "přesměrovat (ne re-route)",
        "od (časově)",
        "podpora, podporovat",
        "ověřit si, prověřit",
        "nastavení(ne setting)",
        "odstranit(ne erase,delete,cle",
        "jednotlivý,osamocený,samostatný",
        "brána",
        "režim",
        "podsíť",
        "použít",
        "následující (ne next)",
        "svazek",
        "k dispozici, dostupný",
        "darovat, přidělit, pověřit",
        "proto,tudíž,takže(ne thus,so)",
        "obdržet,přijmout,dostat(ne acc",
        "obnovit(ze zálohy)(ne recover)",
        "heslo",
        "předvést,ukázat,vystavit,ukázka",
        "adresář (ne složka -folder)",
        "vlastnost (ne feature)",
        "upravit,změnit(ne edit,change)",
        "průzkumník",
        "záloha",
        "pasivovat,zneschopnit(ne inhibi",
        "zpráva (ne report)",
        "nastavení (ne setup)",
        "řídit (ne manage)",
        "testovat,ověřit(ne test,verify)",
        "konto",
        "výpis, seznam",
        "chyba (ne fault,failure,mistake",
        "odpojený(tiskárna)(ne disconne",
        "záznam (ne record)",
        "větev",
        "stanoviště",
        "volitelný",
        "zařízení (ne equipment)",
        "připojit(ne attach,join,add)",
        "vzdálený",
        "připojit,doplnit(ne join,append",
        "přenosný",
        "vytvořit",
        "povolení, oprávnění",
        "předem nastavený(ne preset)",
        "umožnit (ne allow-povolit)",
        "povolit (ne permit,approve)",
        "bezpečnost (ne safety)",
        "přístup",
        "složka (ne adr.-directory)",
        "soubor",
        "uživatel",
        "stát se současně (ne coincide)" ];

cz[6] = [
    "přenos",
    "obecný, běžný, obvyklý",
    "stoh, zásobník",
    "potvrdit např.příjem(ne confirm",
    "potřesení rukou",
    "nedostupný (ne unavailable)",
    "překročit",
    "pročistit (doslova spláchnout)",
    "sada protokolů",
    "vytáčené spojení",
    "zásuvný modul",
    "délka",
    "přenášet,předat dál(ne transmit",
    "občerstvit",
    "nadřazená (rodičovská) složka",
    "zpětné hledání",
    "podmíněný",
    "odpověď",
    "zděděný",
    "řízení přístupu",
    "zřídit spojení",
    "překlad",
    "pořadí zpracování",
    "na vyžádání",
    "vynutit",
    "harmonogram, časový plán",
    "zamýšlený účel",
    "registrace (ne registration)",
    "označit(ne highlight-zvýraznit)",
    "vydavatel",
    "karanténa",
    "způsobilý, oprávněný k čemu",
    "autodiagnostika",                  /*v originálě chybí český popisek*/
    "schválit (ne allow, permit)",
    "uspořádat (ne sort)",
    "spojení (ne link, connection)",
    "zachytit, zaznamenat",
    "čištění",
    "stát se současně, shodovat se s",
    "sbírat (ne gather, pick)",
    "obsahovat",
    "jádro",
    "využití procesoru",
    "prodleva",
    "záviset na",
    "odvozený od",
    "navrhovat (např. síť)",
    "trvání",
    "vymáhání, vynucení",
    "zapsat do seznamu,zaregistrovat",
    "výčet, vyjmenování",
    "vyhodnotit,ověřit,posoudit",
    "identifikovat, určit, zjistit",
    "okamžitě",
    "směřující dovnitř, příchozí",
    "inventura",
    "latence, zdržení",
    "monitorovat,sledovat(ne observe",
    "připojit(např.disk, ne connect)",
    "vyjednávání(např. o protokolu)",
    "pořadí (ne sequence)",
    "táhnout (ne drag)",
    "vyčistit(ne clean),vymazat",
    "snížit, redukovat",
    "řešit (překládat) dotazy (DNS)",
    "získat zpět,vrátit,vyzvednout",
    "zjistit, vyhledat informaci",
    "pravidlo",
    "uspokojit požadavek",
    "načasovaný,s nast.časem spuštěn",
    "rozštěpený, rozdělený",
    "starý,neplatný(ne outdated,obs",
    "provoz přenášených dat",
    "přechod",
    "spouštěcí akce",
    "ověřit kým (ne verify by)",
    "zahájit",
    "považovat",
    "neočekávaně",
    "vyvolávat co (ne excite)",
    "důvěrný",
    "sledovat co, dodržovat co",
    "vyřadit z provozu",
    "účinek (ne effect)",
    "vyjmenovat, vyčíslit",
    "odběr, předplatné",
    "vzájemný, oboustranný",
    "šířka pásma",
    "práh",
    "náhrobek, záznam o smazaném",
    "úvodní byte" ];

cz[7] = [ "přerušit,ukončit(ne break,inter",
        "připojit na konec,doplnit",
        "porovnat",
        "podmínka",
        "odstraňovat chyby (ne troublesh",
        "výraz (ne statement=příkaz)",
        "hromada, halda",
        "odsadit (při psaní)",
        "záznam,věta",
        "odkaz,zmínka(ne referral)",
        "odkaz (ne reference, link)",
        "rozsah(ne span,range),r.platnos",
        "přerušit(ne pause,interrupt,abo",
        "proměnná",
        "uvozovky",
        "' (apostrof)",
        "kontrola, zda něco páruje",
        "krokovat program (ne debug)",
        "ukázat (ne point)",
        "krok",
        "bod přerušení",
        "vyhodnocení logic. výrazu",
        "podmíněný příkaz(ne command)",
        "vnořená smyčka",
        "vývojový diagram",
        "ukázat (ne show)",
        "ukazatel",
        "dědičnost",
        "nasazení",
        "proud (ne flow)",
        "překladač",
        "příznak",
        "spojit (řetězce)",
        "zásobník volání",
        "zaváděcí program",
        "pasivovaný",
        "start",
        "jinak",
        "smyčka",
        "zatímco",
        "spodní mez",
        "výstup",
        "#",
        "ladicí program",
        "počet",
        "zdrojový soubor",
        "podařit se",
        "vyjmout,vyloučit(ne eliminate)",
        "zahrnout, obsahovat(ne contain)",
        "strop",
        "podlaha",
        "síla, výkon (ne performance)",
        "návěští",
        "varování",
        "vrátit (ne retrieve)",
        "neplatný (ne invalid)",
        "rezervace místa v paměti",
        "nekonečno",
        "přetečení",
        "zabalit (ne pack)",
        "ignor.rozdíl mezi m.a v.písm.",
        "čekat",
        "ukončit(ne break,abort,finish)",
        "sekvence volání",
        "různý, rozličný (ne various)",
        "hranice,okraj(ne outline:obrys)",
        "omezení(ne restriction,limit)",
        "výška",
        "šířka",
        "s měnitelným rozměrem",
        "pole (ne field)",
        "interpunkční znaménko",
        "přírůstek",
        "větvení",
        "srovnání",
        "zdrojový kód",
        "kontrola, kontrolovat",
        "prohození, prohodit",
        "řešení",
        "vnořený (kaskád.) příkaz if",
        "naplnit pole",
        "rozhodovací příkaz" ];




/* ================================== EN ==================================*/
en[0] = ["alternative",
        "arrow keys",
        "asterisk",
        "back up",
        "backslash",
        "bar menu",
        "blink",
        "box",
        "break",
        "built in",
        "cancel",
        "capital letter",
        "card",
        "chapter",
        "character",
        "erase",
        "close",
        "colon",
        "column",
        "comma",
        "cut",
        "dash",
        "density",
        "dot",
        "disk drive",
        "duplication",
        "edit",
        "fail",
        "fault",
        "figure",
        "find",
        "general",
        "guide",
        "hide",
        "hyphen",
        "introduction",
        "invalid",
        "letter",
        "line",
        "line-feed",
        "lock",
        "lookup",
        "match",
        "matrix",
        "next",
        "notice",
        "on-line",
        "overwrite",
        "page",
        "part",
        "pick",
        "protect",
        "push",
        "quit",
        "exit",
        "ready",
        "replace",
        "resume",
        "retry",
        "rewrite",
        "ribbon",
        "row",
        "save",
        "seek",
        "scan",
        "select",
        "semicolon",
        "sentence",
        "set",
        "shift",
        "size",
        "slash",
        "standalone",
        "store",
        "switch on",
        "temperature",
        "toggle",
        "topic",
        "total",
        "track",
        "unauthorized",
        "updated",
        "view",
        "binary",
        "level",
        "insufficient",
        "empty",
        "enter",
        "date",
        "sure",
        "miss",
        "failure",
        "recover",
        "proceed",
        "another",
        "hidden",
        "more",
        "brief",
        "full",
        "swap",
        "visible",
        "fast",
        "neither",
        "even" ];

en[1] = [ "tree",
        "folder hierarchy",
        "compress",
        "press",
        "any",
        "dimmed commands",
        "unavailable",
        "clear check box",
        "select check box",
        "shaded check box",
        "font size",
        "point size",
        "bold",
        "italic",
        "underlined",
        "subscript",
        "superscript",
        "insertion point",
        "mouse pointer",
        "shortcut",
        "drag-and-drop",
        "scroll bar",
        "requirement",
        "leave",
        "intact",
        "initial",
        "recommend",
        "at least",
        "as needed",
        "in use",
        "from list",
        "screen saver",
        "uppercase",
        "lowercase",
        "status bar",
        "attachment",
        "paragraph mark",
        "occurrence",
        "check",
        "correct",
        "adjust position",
        "blank line",
        "highlighted text",
        "outline",
        "interrupt",
        "template",
        "caption",
        "drag",
        "resize",
        "relative to",
        "collapse",
        "expand",
        "promote",
        "demote",
        "shortcut menu",
        "customize",
        "spelling",
        "spell checker",
        "annotations",
        "summary info",
        "print preview",
        "header",
        "footer",
        "paper size",
        "portrait",
        "landscape",
        "paragraph",
        "alignment",
        "recently used",
        "match case",
        "case sensitivity",
        "toolbar",
        "forward",
        "backward",
        "spreadsheet",
        "cell",
        "enter data",
        "decimal places",
        "text wrapping",
        "overflow",
        "equal sign",
        "division operator",
        "addition operator",
        "subtraction",
        "greater than",
        "equal to",
        "less than",
        "not equal to",
        "cell reference",
        "pie chart",
        "tile",
        "magnification",
        "sort by",
        "ascending",
        "descending" ];

en[2] = [ "lid",
        "sleep",
        "known",
        "restriction",
        "belong",
        "unique",
        "assignment",
        "expire",
        "inhibit",
        "rights",
        "revoke",
        "everyone",
        "group",
        "queue",
        "status",
        "attach",
        "log in",
        "notify",
        "service",
        "peer-to-peer",
        "intruder",
        "lockout",
        "emergency",
        "update",
        "remain",
        "supress",
        "description",
        "reject",
        "hold",
        "defer",
        "sequence",
        "submit print job",
        "according to",
        "search pattern",
        "trustee",
        "discard",
        "delimiter",
        "dedicated",
        "replica",
        "including",
        "advantage",
        "regardless",
        "prior to",
        "regarding",
        "suspect",
        "loss",
        "legible",
        "approximate",
        "suffer",
        "improve",
        "concern",
        "purpose",
        "estimate",
        "node",
        "query",
        "reliability",
        "edition",
        "providing",
        "delivery",
        ")",
        "violate",
        "sense",
        "benefit",
        "excite",
        "offer",
        "comprise",
        "pace",
        "necessary",
        "demand",
        "similar",
        "join",
        "vendor",
        "manner",
        "reason",
        "reside",
        "suite",
        "kit",
        "grade",
        "auditing",
        "daylight saving time",
        "forwarding",
        "frame",
        "log file",
        "fundamental",
        "take advantage",
        "utilize",
        "independent",
        "whether",
        "describe",
        "locate",
        "major",
        "process",
        "inoperable",
        "direct",
        "abbreviation",
        "distinguish",
        "different",
        "gather",
        "responsibility",
        "layer",
        "term",
        "caution",
        "upon completion",
        "wide range",
        "tune",
        "statement",
        "command",
        "accidental",
        "occasional",
        "random"];

en[3] = [ "dashboard",
        "exact",
        "overall",
        "various",
        "suppose",
        "recognize",
        "advance",
        "executable",
        "placed",
        "flow",
        "launch",
        "highlight",
        "except",
        "compound",
        "beyond",
        "bypass",
        "effort",
        "persistent",
        "facilitate",
        "obsolete",
        "consistent with",
        "comply with",
        "taskbar",
        "commit",
        "gather",
        "obtain",
        "acquire",
        "gain",
        "concurrent",
        "connection",
        "stand alone",
        "wired",
        "binding",
        "search order",
        "performance",
        "send",
        "uninterruptible",
        "power supply",
        "low battery",
        "local",
        "password age",
        "permit",
        "distributed",
        "idle",
        "last known",
        "roam",
        "dial tone",
        "exclude range",
        "automate",
        "hang up",
        "transmit",
        "challenge",
        "response",
        "respond to",
        "lease duration",
        "trust",
        "most restrictive",
        "restrict access",
        "unattended",
        "attend",
        "option",
        "validation",
        "mice",
        "throughput",
        "severe",
        "simple",
        "maintain",
        "maintenance",
        "selection",
        "propose",
        "implement",
        "provide",
        "increase",
        "reveal",
        "overhead",
        "deliver",
        "emulate",
        "damage",
        "eliminate",
        "capability",
        "sensitive",
        "considerable",
        "retain",
        "preserve",
        "efficient",
        "span",
        "regular",
        "encounter",
        "generic",
        "cause",
        "pending",
        "avoid",
        "override",
        "applicable",
        "subset",
        "guarantee",
        "assert",
        "ensure",
        "stress",
        "handle",
        "measure",
        "counter",
        "sluggish",
        "excessive",
        "stuck",
        "loose",
        "corrupt(ed)",
        "buffer",
        "broadcast",
        "load balancing",
        "name resolution",
        "read ahead",
        "rights inheritance",
        "socket",
        "swap file" ];

en[4] = [ "achieve",
        "alert",
        "continue",
        "corporate",
        "destination",
        "determine",
        "equipped",
        "outbound",
        "outdated",
        "permanent",
        "prepare",
        "reach",
        "submit",
        "temporary",
        "unit",
        "utilization",
        "bridge",
        "button",
        "desired",
        "extension",
        "frequently",
        "input",
        "item",
        "protection",
        "recent",
        "accomplish",
        "compliant",
        "compliance",
        "confirm",
        "enterprise",
        "mandatory",
        "prohibited",
        "repair",
        "wrong",
        "browse",
        "environment",
        "execute",
        "particular",
        "range",
        "result",
        "signature",
        "source",
        "resource",
        "supply",
        "stripe",
        "trace",
        "valid",
        "value",
        "background",
        "certain",
        "exception",
        "failed",
        "progress",
        "provided",
        "related",
        "release",
        "solve",
        "via",
        "within",
        "ability",
        "compatibility",
        "daily",
        "entry",
        "example",
        "quickly",
        "accept",
        "incoming",
        "insert",
        "original",
        "portion",
        "separate",
        "smart",
        "verification",
        "appear",
        "occur",
        "case",
        "credentials",
        "deny",
        "hibernation",
        "link",
        "means",
        "point",
        "pool",
        "screen",
        "tool",
        "alternate",
        "detection",
        "disconnect",
        "proper",
        "search",
        "troubleshoot",
        "amount",
        "cartridge",
        "connectivity",
        "examine",
        "host",
        "multiple",
        "multiply",
        "note",
        "ownership",
        "reset",
        "troubleshooting",
        "content",
        "deploy",
        "likely",
        "listed",
        "prompt",
        "safe",
        "additional",
        "bar",
        "based",
        "encrypt",
        "hub",
        "issue",
        "language",
        "pack",
        "partition",
        "technician",
        "feature",
        "load",
        "location",
        "previous",
        "request",
        "resolution",
        "whenever",
        "employee",
        "include" ];

en[5] = [ "move",
        "package",
        "personal",
        "unsigned",
        "development",
        "member",
        "path",
        "session",
        "current",
        "custom",
        "event",
        "image",
        "several",
        "legacy",
        "thus",
        "appropriate",
        "assign",
        "cookie",
        "root",
        "wireless",
        "controller",
        "establish",
        "state",
        "unable",
        "discover",
        "furthermore",
        "private",
        "roaming",
        "storage",
        "switch",
        "wizard",
        "affect",
        "delete",
        "incremental",
        "located",
        "running",
        "solution",
        "trusted",
        "authentication",
        "key",
        "research",
        "dial",
        "resolve",
        "through",
        "boot",
        "clear",
        "task",
        "successfully",
        "update",
        "attempt",
        "choose",
        "require",
        "consist",
        "flexible",
        "upgrade",
        "manager",
        "advanced",
        "change",
        "manage",
        "report",
        "space",
        "tab",
        "apply",
        "driver",
        "share",
        "perform",
        "router",
        "interface",
        "prevent from",
        "redirect",
        "since",
        "support",
        "verify",
        "setup",
        "remove",
        "single",
        "gateway",
        "mode",
        "subnet",
        "use",
        "following",
        "volume",
        "available",
        "grant",
        "therefore",
        "receive",
        "restore",
        "password",
        "exhibit",
        "directory",
        "property",
        "modify",
        "explorer",
        "backup",
        "disable",
        "message",
        "setting",
        "control",
        "check",
        "account",
        "list",
        "error",
        "offline",
        "log",
        "branch",
        "site",
        "optional",
        "device",
        "connect",
        "remote",
        "add",
        "portable",
        "create",
        "permission",
        "default",
        "enable",
        "allow",
        "security",
        "access",
        "folder",
        "file",
        "user",
        "collide" ];

en[6] = [ "transfer",
        "common",
        "stack",
        "acknowledge",
        "handshake",
        "unreachable",
        "exceed",
        "flush",
        "protocol suite",
        "dial-up connection",
        "snap-in",
        "length",
        "relay",
        "refresh",
        "parent folder",
        "reverse lookup",
        "conditional",
        "answer",
        "inherited",
        "access control",
        "set up a connection",
        "translation",
        "processing order",
        "on demand",
        "enforce",
        "schedule",
        "intended purpose",
        "enrolment",
        "mark",
        "publisher",
        "quarantine",
        "eligible",
        "selftest",
        "approve",
        "arrange",
        "association",
        "capture",
        "cleanup",
        "coincide",
        "collect",
        "contain",
        "core",
        "CPU utilization",
        "delay",
        "depend on",
        "derived from",
        "design",
        "duration",
        "enforcement",
        "enlist",
        "enumeration",
        "evaluate",
        "identify",
        "immediately",
        "inbound",
        "inventory",
        "latency",
        "monitor",
        "mount",
        "negotiation",
        "order",
        "pull",
        "purge",
        "reduce",
        "resolve queries",
        "retrieve",
        "retrieve",
        "rule",
        "satisfy requirement",
        "scheduled",
        "split",
        "stale",
        "transfer traffic",
        "transition",
        "trigger",
        "validate by",
        "initiate",
        "consider",
        "unexpectedly",
        "invoke",
        "confidential",
        "observe",
        "decommission",
        "impact",
        "enumerate",
        "subscription",
        "mutual",
        "bandwidth",
        "threshold",
        "tombstone",
        "preamble byte" ];

en[7] = [ "abort",
        "append",
        "compare",
        "condition",
        "debug",
        "expression",
        "heap",
        "indent",
        "record",
        "reference",
        "referral",
        "scope",
        "suspend",
        "variable",
        "double quotes",
        "single quotes",
        "pair matching",
        "trace",
        "show",
        "step",
        "breakpoint",
        "boolean evaluation",
        "conditional statement",
        "nested loop",
        "flow chart",
        "point",
        "pointer",
        "inheritance",
        "deployment",
        "stream",
        "compiler",
        "flag",
        "concatenate",
        "call stack",
        "loader",
        "disabled",
        "startup",
        "else",
        "loop",
        "while",
        "lower bound",
        "output",
        "hash",
        "debugger",
        "count",
        "source file",
        "succeed",
        "exclude",
        "include",
        "ceiling",
        "floor",
        "power",
        "label",
        "warning",
        "return",
        "void",
        "memory allocation",
        "infinity",
        "overflow",
        "wrap",
        "ignore case",
        "wait",
        "terminate",
        "call sequence",
        "miscellaneous",
        "border",
        "constraints",
        "height",
        "width",
        "resizable",
        "array",
        "punctuation",
        "increment",
        "choice",
        "comparison",
        "source code",
        "check",
        "swap",
        "solution",
        "cascading if statement",
        "populate an array",
        "decision statement"];